adminUser:
  password: vault:burndiamond/adminUser:password
  username: admin
dashboardAuthID: vault:burndiamond:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:burndiamond:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:burndiamond/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:burndiamond/prow:hmacToken
